source 'https://rubygems.org'

require 'active_record'
require 'tiny_tds'
require 'activerecord-sqlserver-adapter'
require 'pp'

# gem 'rake'
# gem 'rspec'
# gem 'watir-rspec'
# gem 'watir'
# gem 'webdrivers'
# gem 'watir_drops'
# gem 'watir_model'
# gem 'data_magic'
# gem 'require_all'
# gem 'sauce_whisk'

# gem 'allure-rspec'
# gem 'test-page'

# gem 'watir_install'

# gem 'webdriver_manager'
# gem 'config_model'
# gem 'ui2api'
# gem 'active_emoji'
# gem 'airborne'
# gem 'chunky_png'
# gem 'emoji-rspec'
# gem 'faker'
# gem 'ffaker'
# gem 'httpclient'
# gem 'insite'
# gem 'json'
# gem 'knapsack'
# gem 'machinist'
# gem 'nokogiri'
# gem 'pairwise'
# gem 'parallel_tests'
# gem 'paraspec'
# gem 'pry'
# gem 'ruby-jmeter'
# gem 'spreadsheet_architect'
# gem 'stealth'
# gem 'tap_watir'
# gem 'TestFactory'
# gem 'timecop'
# gem 'webdriver-user-agent'
# gem 'watigiri'
# gem 'watir_angular'
# gem 'watir-css'
# gem 'watir_pump'
# gem 'watir-scroll'
# gem 'watir-webdriver-performance'
# gem 'watir-extensions-element-screenshot'
# gem 'watir-screenshot-stitch'
# gem 'watir-get-image-content'
# gem 'watir-dom-wait'
# gem 'watir-scroll'
# gem 'watir-timecop'
